version: '2'
services:
    medianoche-app:
        image: medianoche
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://medianoche-postgresql:5432/medianoche
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    medianoche-postgresql:
        extends:
            file: postgresql.yml
            service: medianoche-postgresql
